Create a random tensor with shape (7,7)

In [ ]:
import torch

tensor_A = torch.rand(7,7)
tensor_A.shape

torch.Size([7, 7])

Perform a matrix multiplication on the tensor above with anotehr random tensor with shape (1,7)

In [ ]:
tensor_B = torch.rand(1,7)
tensor_B

tensor([[0.8345, 0.5345, 0.5806, 0.9452, 0.1132, 0.2386, 0.5841]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[1.5329],
        [2.2457],
        [1.3552],
        [1.7108],
        [1.9519],
        [1.8255],
        [2.1204]])

Set the random seed to 0, then do the previous two questions again


In [ ]:
torch.manual_seed(0)
tensor_A = torch.rand(7,7)

torch.manual_seed(0)
tensor_B = torch.rand(1,7)

torch.mm(tensor_A, tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

Is there a GPU equivalent to torch.manual_seed()

In [ ]:
torch.cuda.manual_seed(1234)

Create two random tensors of shape (2,3), send them both to the GPU. set torch.manual_seed(1234).

In [ ]:
import torch
torch.manual_seed(1234)
tensor_A = torch.rand(2,3)

torch.manual_seed(1234)
tensor_B = torch.rand(2,3)

# check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = tensor_A.to(device)
tensor_B = tensor_B.to(device)

print(tensor_A, tensor_B)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


Perform a matrix multiplication on the tensors you created

In [ ]:
tensor_C = torch.mm(tensor_A, tensor_B.T)
tensor_C

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

Find the maximum and minimum index values of the output

In [ ]:
tensor_C.argmax()

tensor(3, device='cuda:0')

In [ ]:
tensor_C.argmin()

tensor(1, device='cuda:0')

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left wwitha tensor of shape (10), set the seed to 7 when you create it and print out the first tensor and its shape as well as the second tensor and its shape

In [ ]:
torch.manual_seed(7)
tensor_A = torch.rand(1, 1, 1, 10)
tensor_B = torch.squeeze(tensor_A)
print(tensor_A, tensor_A.shape)
print(tensor_B, tensor_B.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
